In [2]:
import pandas as pd

In [10]:
# Que no haya límite en número de columnas
pd.set_option('display.max_columns', None)

# Ajustes opcionales para que no quiebre líneas
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [114]:
df = pd.read_csv('/mnt/d/home-2/Documentos/master/practica-deusto-tech/TFM/tdbench-supp-clean/data_mode_switch_results.csv', nrows=10000000)
df.head()

:

In [101]:
df.columns

Index(['Subset', 'Score', 'Default Train Time', 'Opt Train Time',
       'Opt Train Time Total', 'Hostname', 'Data Distill Time',
       'Inference Time', 'Dataset', 'Classifier', 'N', 'Data Parse Mode',
       'Post Data Parse Mode', 'Data Mode', 'Distill Method', 'Encoder',
       'Distill Space', 'Output Space', 'Convert Binary', 'Cluster Center',
       'Short Name'],
      dtype='object')

In [102]:
df.Dataset.unique()

array(['Adult', 'AmazonEmployeeAccess', 'BankMarketing', 'Credit',
       'CreditDefault', 'Diabetes', 'Electricity', 'Elevators', 'Higgs',
       'HomeEquityCredit', 'House', 'Jannis', 'LawSchoolAdmissions',
       'MagicTelescope', 'MedicalAppointments', 'MiniBooNE', 'NumerAI',
       'Nursery', 'PhishingWebsites', 'Pol', 'RoadSafety',
       'TencentCTRSmall', 'TwoDPlanes'], dtype=object)

In [103]:
df_sub = df[(df.Dataset == 'Adult') & (df.Classifier == 'XGBClassifier') & (df.Subset == 'Test')]

In [104]:
df_sub['Distill Method'].unique()

array(['Original', 'Random Sample', 'KMeans', 'Agglo', 'KIP', 'GM'],
      dtype=object)

In [105]:
{i:type(i) for i in df_sub['Encoder'].unique()}

{nan: float,
 'MLP': str,
 'GNN': str,
 'TF': str,
 'MLP-MultiHead': str,
 'GNN-MultiHead': str,
 'TF-MultiHead': str}

In [106]:
df_sub['Output Space'].unique()

array(['original', 'decoded', 'encoded'], dtype=object)

In [107]:
df_sub.Score.unique()

array([0.84407227, 0.69390093, 0.76337954, ..., 0.78121831, 0.76748548,
       0.78745755], shape=(3810,))

In [108]:
df_sub.N.unique()

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
import numpy as np
df_sub_ori = df_sub[(df_sub['Encoder'].isna())]
df_sub_k_ori = df_sub[(df_sub['Distill Method'] == 'KMeans') & 
                    (df_sub['Output Space'] == 'decoded') & 
                    (df_sub['Encoder'] == 'TF') & (df_sub['Convert Binary'] == False) & (df_sub['Cluster Center'] == 'centroid')]
df_sub_lat = df_sub[(df_sub['Distill Method'] == 'KMeans') & 
                    (df_sub['Output Space'] == 'decoded') & 
                    (df_sub['Encoder'] == 'TF') & (df_sub['Convert Binary'] == False) & (df_sub['Cluster Center'] == 'centroid')]
df_sub_lat_ft = None

In [110]:
df_sub_ori.head()

,Subset,Score,Default Train Time,Opt Train Time,Opt Train Time Total,Hostname,Data Distill Time,Inference Time,Dataset,Classifier,N,Data Parse Mode,Post Data Parse Mode,Data Mode,Distill Method,Encoder,Distill Space,Output Space,Convert Binary,Cluster Center,Short Name
3,Test,0.844072,50.62914,0,0,Unknown,-1.0,0.060452,Adult,XGBClassifier,10,mixed,mixed,Mixed -> Original -> Mixed,Original,NaN,NaN,original,False,centroid,Mixed -> ORI -> Mixed
31,Test,0.844072,50.62914,0,0,Unknown,-1.0,0.060452,Adult,XGBClassifier,20,mixed,mixed,Mixed -> Original -> Mixed,Original,NaN,NaN,original,False,centroid,Mixed -> ORI -> Mixed
59,Test,0.844072,50.62914,0,0,Unknown,-1.0,0.060452,Adult,XGBClassifier,30,mixed,mixed,Mixed -> Original -> Mixed,Original,NaN,NaN,original,False,centroid,Mixed -> ORI -> Mixed
87,Test,0.844072,50.62914,0,0,Unknown,-1.0,0.060452,Adult,XGBClassifier,40,mixed,mixed,Mixed -> Original -> Mixed,Original,NaN,NaN,original,False,centroid,Mixed -> ORI -> Mixed
115,Test,0.844072,50.62914,0,0,Unknown,-1.0,0.060452,Adult,XGBClassifier,50,mixed,mixed,Mixed -> Original -> Mixed,Original,NaN,NaN,original,False,centroid,Mixed -> ORI -> Mixed

In [113]:
df_sub_lat.groupby(['N']).mean('Score')

,Score,Default Train Time,Opt Train Time,Opt Train Time Total,Data Distill Time,Inference Time,Convert Binary
N,,,,,,,
10,0.511684,7.581582,0.0,0.0,1.827292,0.024767,0.0
20,0.547647,8.309161,0.0,0.0,2.508125,0.025673,0.0
30,0.546469,8.798650,0.0,0.0,2.763332,0.025916,0.0
40,0.515986,10.737927,0.0,0.0,2.609129,0.024637,0.0
50,0.524812,13.247626,0.0,0.0,2.372739,0.025192,0.0
60,0.546735,14.707613,0.0,0.0,2.050787,0.023573,0.0
70,0.537585,15.948046,0.0,0.0,2.317299,0.023523,0.0
80,0.526142,16.466061,0.0,0.0,2.200292,0.025553,0.0
90,0.568886,17.363613,0.0,0.0,2.270423,0.022807,0.0
100,0.584183,18.330395,0.0,0.0,2.396002,0.024653,0.0