In [35]:
import pandas as pd

In [44]:
df = pd.read_csv('checkpoint_shoppers_Dlatent_F/metrics.csv')
df.head()

,model,method,cv_balanced,cv_macro_f1,cv_weighted_f1,cv_accuracy,cv_balanced_std,cv_macro_f1_std,cv_weighted_f1_std,cv_accuracy_std,...,test_accuracy,test_roc_auc,inf_time_per_sample,space,IPC,seed,vae_pretrain_time,vae_fine_tunning_time,encoder_inference_time,decoder_inference_time
0,mlp,k-means,0.35,0.240,0.240,0.35,0.200,0.131,0.131,0.200,...,0.826,0.604,0.000017,latent,10,5,0,0,0,0.564191
1,mlp,k-means,0.40,0.353,0.353,0.40,0.255,0.251,0.251,0.255,...,0.680,0.655,0.000013,latent,10,6,0,0,0,0.001252
2,mlp,k-means,0.60,0.580,0.580,0.60,0.200,0.210,0.210,0.200,...,0.840,0.647,0.000025,latent,10,7,0,0,0,0.001260
3,mlp,k-means,0.45,0.360,0.360,0.45,0.187,0.196,0.196,0.187,...,0.164,0.494,0.000020,latent,10,8,0,0,0,0.001268
4,mlp,k-means,0.55,0.507,0.507,0.55,0.245,0.271,0.271,0.245,...,0.782,0.731,0.000009,latent,10,9,0,0,0,0.001279

In [ ]:
# MPL

(df.groupby('IPC')['test_balanced']
                       .agg(['mean', 'std'])
                       .reset_index())

In [ ]:
# XGB

(df.groupby('IPC')['test_balanced']
                       .agg(['mean', 'std'])
                       .reset_index())

In [32]:
# XGB destilando con CLS 

(df.groupby('IPC')['test_balanced']
                       .agg(['mean', 'std'])
                       .reset_index())

   IPC    mean       std
0   10  0.7936  0.057025
1   20  0.7520  0.087878
2   30  0.7968  0.062647
3   40  0.8170  0.023728
4   50  0.8164  0.028580
5   60  0.8270  0.013323
6   70  0.8290  0.011113
7   80  0.8340  0.012227
8   90  0.8388  0.016239
9  100  0.8366  0.014046

In [41]:
# XGB entrenando en latente con solo cls

(df.groupby('IPC')['test_balanced']
                       .agg(['mean', 'std'])
                       .reset_index())

   IPC    mean       std
0   10  0.6022  0.050806
1   20  0.6220  0.031906
2   30  0.6404  0.051228
3   40  0.6414  0.056787
4   50  0.6328  0.047668
5   60  0.6298  0.045428
6   70  0.6428  0.035577
7   80  0.6404  0.036350
8   90  0.6488  0.034405
9  100  0.6550  0.044760

In [45]:
# mlp entrenando en latente con solo cls

(df.groupby('IPC')['test_balanced']
                       .agg(['mean', 'std'])
                       .reset_index())

   IPC    mean       std
0   10  0.5798  0.084636
1   20  0.5378  0.078532
2   30  0.6148  0.062428
3   40  0.6208  0.069211
4   50  0.6444  0.041344
5   60  0.6112  0.060837
6   70  0.6378  0.054961
7   80  0.6476  0.028157
8   90  0.6668  0.041794
9  100  0.6362  0.017167